### ISSUE TITLE
Issues with folder names while importing bibtex entry

### ISSUE THREAD

**Issue by dcoeurjo** [wowchemy/bibtex-to-markdown#123]
After a clean reinstall of academic (`pip install -U academic`), I've got several issues importing a bibtex entry:

- without the `--normalize` the tool does not follow the bibtex tag when creating the folder. (eg. tag doigniesQMCDiffusion → folder doignies-qmc-diffusion)
- after the folder is created, the tool was able to copy the `cite.bib` but fails to edit the `index.md`
 
        FileNotFoundError: [Errno 2] No such file or directory: '/....../path..../...../doignies-qmc-diffusion/index.md'

Have you already experimented such a thing ?

(academic version: 0.8.1)

**Comment by gcushen** [comment]
> (academic version: 0.8.1)

v0.8.1 is a very old version from 2021. Try to use the latest version (**v0.9.1**) and it should work successfully.

> without the --normalize the tool does not follow the bibtex tag when creating the folder. (eg. tag doigniesQMCDiffusion → folder doignies-qmc-diffusion)

This is the intended function of the normalize option based on web best practices and Hugo's URL structures.

**Comment by dcoeurjo** [comment]
Thanks for the feedback. I was following the install instructions in the readme.
Should I use : 

       pip install -U git+https://github.com/wowchemy/bibtex-to-markdown.git 

?

**Comment by gcushen** [comment]
The installation is the same as any other Python package. You can use the same installation command from the GitHub README: `pip3 install -U academic`.

**Alternatively**, you can also try an even easier installation with [Pipx](https://pypa.github.io/pipx/) (`pipx install academic`) which will automatically install the correct Python version for you in a dedicated environment.

**Comment by dcoeurjo** [comment]
That is strange.. but the pip install gives me the 0.8.1. I'll try with pipx 

Thanks for your help

**Comment by dcoeurjo** [comment]
All good with pipx... (not sure what's wrong with my pip..)

Thanks for your help
