### ISSUE TITLE
Remove dependency on Hugo

### ISSUE THREAD

**Issue by gcushen** [wowchemy/bibtex-to-markdown#85]
# Background

Merging of #68 introduced a dependency on Hugo by using the `hugo new` command.

Users have reported that the Academic tool can now be more difficult to use given the dependencies that are needed to run the tool locally.

Make Hugo an _optional_ requirement again so that users can continue to generate publication files locally and upload them to GitHub without needing to install Hugo and its dependencies locally. This change would provide a portable solution, making it easier to also use the Academic CLI with other static site generators.

# Proposal

Based on https://github.com/wowchemy/hugo-academic-cli/pull/73#issuecomment-696653807

**Comment by ionlights** [comment]
I've already made some progress on this. I think I'll be able to knock it out over this coming weekend, though.

**Comment by cyriltw** [comment]
> I've already made some progress on this. I think I'll be able to knock it out over this coming weekend, though.

I came searching for the same problem and wondering if this issue was fixed.

**Comment by gcushen** [comment]
Fixed by #121
